require('prototypes.categories.categories')
require('prototypes.entity.entities')
require('prototypes.autoplace-controls')
require('prototypes.item.items')
require('prototypes.fluid.fluid')
require('prototypes.technology.technology')
require('prototypes.recipe.recipes')
