require('prototypes.entity.explosions')
require('prototypes.entity.machines')
require('prototypes.entity.resources')
require('prototypes.entity.remnants')
require('prototypes.entity.projectiles')
require('prototypes.entity.stickers')
require('prototypes.entity.vehicles')
--require('prototypes.entity.drivers')
